[colors]
	[colors.primary]
		background = "#000000"
		foreground = "#DDDDDD"
	[colors.normal]
		red = "#800000"
		green = "#008000"
		yellow = "#808000"
		blue = "#000080"
		magenta = "#800080"
		cyan = "#008080"
		white = "#DDDDDD"
	[colors.bright]
		red = "#FF0000"
		green = "#00FF00"
		yellow = "#FFFF00"
		blue = "#0000FF"
		magenta = "#FF00FF"
		cyan = "#00FFFF"
		white = "#FFFFFF"
[font]
        normal ={ family =  "Fixedsys Excelsior" }
        size = 12

